name: Auto Create PR for Claude Branches

on:
  push:
    branches:
      - 'claude/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    # Only run if PR doesn't already exist
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract branch info
        id: branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT

          # Get latest commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_msg<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check if PR exists
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --head "${{ steps.branch.outputs.name }}" --json number --jq 'length')
          echo "exists=$PR_EXISTS" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_pr.outputs.exists == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head "${{ steps.branch.outputs.name }}" \
            --title "🤖 Claude Code: $(echo '${{ steps.branch.outputs.commit_msg }}' | head -1)" \
            --body "## Automated Pull Request

          This PR was automatically created from Claude Code changes.

          ### Latest Commit
          \`\`\`
          ${{ steps.branch.outputs.commit_msg }}
          \`\`\`

          ### Branch
          \`${{ steps.branch.outputs.name }}\`

          ### Review
          Please review the changes in the commits tab.

          ---
          🤖 Auto-generated by GitHub Actions when pushing to \`claude/**\` branches"
